### PR TITLE
Update Punic and raise on_locale_load event every time the current locale changes

### PR DESCRIPTION
**Pull request by mlocati**
`PunicData::setDefaultLocale` should be called every time the currently active locale changes.
Not sure about the `on_locale_load` event, though...

### CODE REVIEW

**Comment by ahukkanen** [comment]
I'm actually starting to think could we somehow get the `Punic` stuff out of the `Locaization` class?

Can we call this method only when `Punic` is used? Now, we're calling it even if `Punic` never gets called. It would make this handling a bit more simple.

For the `on_locale_load`, I think its behavior needs to match the old behavior. Now, someone can fire that event just by changing the active context.

**Comment by mlocati** [comment]
> I'm actually starting to think could we somehow get the Punic stuff out of the Locaization class?
> 
> Can we call this method only when Punic is used? Now, we're calling it even if Punic never gets called. It would make this handling a bit more simple.

No, Punic is used in concrete5 helpers (date, number, others?), and could be used directly by packages... And it needs to always know which is the currently active locale...

> For the on_locale_load, I think its behavior needs to match the old behavior. Now, someone can fire that event just by changing the active context.

That event is fired if the new active context uses a different locale (see [here](https://github.com/mainio/concrete5/pull/5/files#diff-301c8bec427c12c1ec46fce50f47d209R106)), and that matches the old behaviour.

**Comment by ahukkanen** [comment]
> No, Punic is used in concrete5 helpers...

Yeah, I was kind of thinking that these helpers would set the locale before calling stuff from Punic. This way, the logic would be decoupled from the Localization internal functionality. I understand someone might call these directly manually but I think in these situations, they could set the locale manually as well.

But if it has to be called, it has to be. I'm just trying to suggest some ways to keep it maybe a bit simpler.

For the event, yeah I can see but how about this:

``` php
$l = Localization::getInstance();
$l->setContextLocale('a', 'fi_FI');
$l->setContextLocale('b', 'sv_SV');

// Let's say active context was 'z' with 'en_US'
$l->setActiveContext('a');
$foo->bar();
$l->setActiveContext('b');
$foo->baz();
$l->setActiveContext('a');
$foo->bar();
```

I mean this situation does not necessarily reflect how the current API works. It now fires the event always when the active context is changed where as in the old API, the event only got fired in case someone called the `setLocale()` method.

But if you are fine with this, I don't have anything against it either. I'm just trying to point out the possible effect on the expected result.

**Comment by mlocati** [comment]
About Punic: I totally agree that switching the context should be as simple (and fast) as possible, but I think that the code is much cleaner if we don't force users to set the Punic locale every time they use a Punic function.
If we remove the Punic code from the Localization class, developers would need to change from

``` php
echo \Punic\Number::format(1.2);
```

to

``` php
echo \Punic\Number::format(1.2, null, \Localization::activeLocale());
```

Another solution they could be tempted to do could be

``` php
\Punic\Data::setDefaultLocale(\Localization::activeLocale());
echo \Punic\Number::format(1.2);
```

but changing the Punic default locale could cause side effects in other points of the core or in other packages.

So, yes, I'd keep the Punic stuff in a centralized place (ie the Localization class).

About the event, the problem is that other packages could currently use the `on_locale_load` for two different purposes: to know when a new locale is loaded and to know when the current locale changes.
And that's why, for a better backward compatibility, I'd call it every time the current locale changes...

So (sadly) I think that this new `currentLocaleChanged` method should reman as I'm suggesting in this PR...

**Comment by ahukkanen** [comment]
OK, yeah, makes sense. And I'm perfectly fine with these changes but I just wanted to make sure especially about the event that you are aware of possible implications on the API.

But yeah, perfect backwards compatibility is always tough regarding these types of changes. So, I think I'll just merge this in.

**Comment by mlocati** [comment]
> I just wanted to make sure especially about the event that you are aware of possible implications on the API.

And that's really a good thing! I always think that four eyes are better that two, and that critics are always a good way to fully inspect a problem (well, only if they are positive critics like the ones you are posing :wink: )

**Pull request merged**
