### PR TITLE
Update current locale if changing locale of current context

### PR DESCRIPTION
**Pull request by mlocati**
Here's what I meant with point 3 of [my comment](https://github.com/concrete5/concrete5/issues/3624#issuecomment-202864250)

### CODE REVIEW

**Comment by mlocati** [comment]
An example to explain why this change is needed:
- let's assume the current context is 'a'
- we call Localization->setContextLocale('a', 'locale')

It's the same as calling Localization->setLocale('locale'), so the behaviour should be consistent (otherwise we'd change the current locale without doing [this](https://github.com/mlocati/concrete5/blob/mainio-localization-improvements-8.0.0-2/web/concrete/src/Localization/Localization.php#L160-L163))

**Comment by ahukkanen** [comment]
Hmm, yeah then I think I got your point.

But I'm not sure if I like this approach. I would rather keep the current event where it is and then create a completely new event that gets called in the `setContextLocale()` method, regardless of the active context. How would you feel about that?

**Comment by ahukkanen** [comment]
And just to clarify my point of view: I don't think anyone would be calling `setContextLocale()` in case they are assuming to be using the old API.

**Comment by mlocati** [comment]
Well, calling setContextLocale with the current locale leads to the same effect as setLocale. So, packages that need to do something with the new current locale should be notified too, and keeping the old event won't break BC.
But yes, we could _add_ a new "localizationContextChanged" event

**Comment by ahukkanen** [comment]
That's good point as well.

So, yeah, I think overall this would works in more occasions as expected, so I think it's a good change.

**Pull request merged**
